services:
    frontend:
        build: 
            context: ./frontend/
            args:
                - VITE_BACKEND_URL=http://localhost:8000
                - VITE_BACKEND_URL_API=http://localhost:8000/api/v1
                - VITE_GOOGLE_CLIENT_ID=changeme
        depends_on:
            - backend
        ports:
            - 5173:80

    backend:
        build: .
        container_name: backend
        environment:
            - DB_USER=admin
            - DB_PASSWORD=root
            - DB_URL=mongo
            - PORT=8000
            - ADMIN=true
            - PRIVATE_KEY=changeme
            - GOOGLE_CLIENT_ID=changeme
        ports:
            - 8000:8000
        restart: unless-stopped
        depends_on: 
            - mongo
            - loki
            - promtail
            - prometheus

    mongo:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - 27017:27017
        # Uncomment this to make the db persistent
        # volumes:
        #   - ./db:/data/db

    loki:
        image: grafana/loki:latest
        container_name: loki
        command: -config.file=/etc/loki/loki-config.yaml
        ports:
            - "3100:3100"
        volumes:
            - ./observability/loki/loki-config.yaml:/etc/loki/loki-config.yaml
            
    promtail:
        image: grafana/promtail:latest
        container_name: promtail
        command: -config.file=/etc/promtail/promtail-config.yaml
        volumes:
            - ./observability/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
            - /var/log:/var/log
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - loki

    grafana:
        image: grafana/grafana:11.6.0
        container_name: grafana
        ports:
            - "3000:3000"
        depends_on:
            - loki
            - prometheus

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - 9090:9090
        volumes:
            - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    # Abiltitato solo con il profilo dev
    simulator:
        build:
            context: ./traffic-simulator
        profiles:
            - dev
        depends_on:
            - backend
        ports:
            - 8050:8050
            