{
 "title": "Client_Merchant Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Registered Users",
   "type": "stat",
   "gridPos": { "h": 29, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "registered_clients{instance=\"backend:8000\"}",
     "legendFormat": "Clienti registrati"
    },
    {
     "expr": "registered_merchants{instance=\"backend:8000\"}",
     "legendFormat": "Negozi registrati"
    }
   ]
  },
  {
   "title": "Client actions logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"/backend\"} | json | scope = `client`"
    },
    {
     "direction": "backward",
     "expr": "{container=\"/backend\"} | json | scope = `registration` | msg =~ `.*[Cc]lient.*`"
    },
    {
     "direction": "backward",
     "expr": "{container=\"/backend\"} | json | scope = `shops`"
    }
   ]
  },
  {
   "title": "Merchant actions logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 16, "x": 8, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"/backend\"} | json | scope = `shopsAuth`"
    },
    {
     "direction": "backward",
     "expr": "{container=\"/backend\"} | json | scope = `registration` | msg =~ `.*[Mm]erchant.*`"
    }
   ]
  }
 ]
}