{
 "title": "Transactions dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active transactions",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_transactions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transactions started per minute",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(transaction_count[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total transaction count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transaction_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active transactions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "active_transactions", "legendFormat": "Currently active transactions" }
   ]
  },
  {
   "title": "Transaction completion time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transaction_duration_bucket", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Transaction creation logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"/backend\"} |= `QR assign request` or `QR generated` | json | scope = `qrcode`"
    }
   ]
  },
  {
   "title": "Transaction completion logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"/backend\"} |= `QR code received` or `Assignment QR applied` | json | scope = `qrcode`"
    }
   ]
  },
  {
   "title": "Transaction error logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"/backend\"} |= `err` | json | scope = `qrcode`"
    }
   ]
  }
 ]
}